fileversion: 3

robots:
  cf1:
    enabled: true
    uri: radio://0/80/2M/E7E7E7E7E7
    initial_position: [0.0, 0.0, 0.0]
    type: cf21

robot_types:
  cf21:
    motion_capture:
      tracking: "librigidbodytracker"
      marker:   default_single_marker
      dynamics: default
    big_quad: false
    battery: { voltage_warning: 3.8, voltage_critical: 3.7 }

all:
  firmware_params:
    commander:  { enHighLevel: 1 }
    stabilizer: { estimator: 2, controller: 2 }
    locSrv:     { extPosStdDev: 0.001 }
