<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>thermal_mapping</name>
  <version>0.1.0</version>
  <description>Simulated thermal sensor + shared multi-drone heat map for the CrazySim stack.</description>
  <maintainer email="rk32226@example.com">rk32226</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>grid_map_msgs</depend>
  <depend>thermal_mapping_interfaces</depend>
  <depend>visualization_msgs</depend>
  <depend>coverage_optimizer_interfaces</depend>

  <exec_depend>ros2launch</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>grid_map_rviz_plugin</exec_depend>
  <exec_depend>cf_coverage_planner</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
